repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: |
            (?x)(
              ^.github/
            )
        exclude_types: [markdown, yaml, toml]
      - id: end-of-file-fixer
        exclude: |
            (?x)(
              ^.github/
            )
        exclude_types: [markdown, yaml, toml]
      - id: check-docstring-first
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.270
    hooks:
      - id: ruff
