line-length = 88

[lint]
select = [
    "A",
    "B",
    "C4",
    "COM",
    "D",
    "DTZ",
    "E",
    "EM",
    "F",
    "ISC",
    "N",
    "NPY",
    "PD",
    "PT",
    "PTH",
    "Q",
    "T10",
    "T20",
    "W",
    "YTT",
]
ignore = ["N812", "PD901", "E712", "E721"]

[lint.pydocstyle]
convention = "numpy"

[lint.flake8-quotes]
inline-quotes = "double"

[lint.per-file-ignores]
"*/__init__.py" = ["D104"]
"*/" = ["B006", "PTH123", "B008"]
"tests/*" = ["ANN", "D100", "E501", "F403", "F405", "PT011", "B017", "D205"]
