[tool.poetry]
name = "rdsa-utils"
version = "0.1.0-dev0"
description = ""
authors = ["Reproducible Data Science & Analysis, ONS"]
maintainers = [
   "Matthew Price <Matthew.G.Price@ons.gov.uk>",
]

readme = "README.md"
repository = "https://github.com/ONSdigital/rdsa-utils"
documentation = "https://github.com/ONSdigital/rdsa-utils"


[tool.poetry.dependencies]
python = "^3.7"
bs4 = "^0.0.1"
jinja2 = "^3.1.2"


[tool.poetry.group.dev.dependencies]
pytest = "^7.1.0"
pytest-cov = "^4.0.0"
pytest-lazy-fixture = "^0.6.0"
pytest-mock = "^3.8.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
