name: Version and Branch Check on PR to Main

on:
  pull_request:
    branches: [main]

jobs:
  check-branch-and-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necessary to fetch all history for tags and branches

      - name: Check branch name
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          echo "Branch name is: $BRANCH_NAME"
          if [ "$BRANCH_NAME" != "development" ]; then
            echo "::error ::Pull requests can only be merged from the 'development' branch into 'main'. Your branch is named '$BRANCH_NAME'."
            exit 1
          fi
        shell: bash

      - name: Extract versions and compare
        run: |
          # Extracting version from development branch (HEAD of PR)
          DEV_VERSION=$(grep -Eo "__version__ = '.*'" rdsa_utils/__init__.py | cut -d"'" -f2 || python setup.py --version)
          echo "Version in development branch: $DEV_VERSION"

          # Fetching the main branch
          git fetch origin main:main
          
          # Extracting version from main branch
          MAIN_VERSION=$(git show main:rdsa_utils/__init__.py | grep -Eo "__version__ = '.*'" | cut -d"'" -f2 || git show main:setup.py | grep -Po "(?<=version=')\d+\.\d+\.\d+(?=')")
          echo "Version in main branch: $MAIN_VERSION"

          # Compare versions
          if [ "$(printf '%s\n' "$DEV_VERSION" "$MAIN_VERSION" | sort -V | head -n1)" = "$MAIN_VERSION" ] && [ "$DEV_VERSION" != "$MAIN_VERSION" ]; then
            echo "Version check passed. Development version ($DEV_VERSION) is higher than main version ($MAIN_VERSION)."
          else
            echo "::error ::Version in development branch ($DEV_VERSION) is not higher than in main branch ($MAIN_VERSION). You must increment the version."
            exit 1
          fi
        shell: bash
